name: hanal_3d
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  ar_flutter_plugin_updated: ^0.0.1
  path_provider: ^2.0.0
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/altar_de_dia_de_muertos.glb
    - assets/dia_de_los_muertos.glb
    - assets/dia_de_los_muertos_katrina_mexico.glb
    - assets/papel_picado.glb
    - assets/skull_dia_de_muertos.glb
